version: 2
registries:
  ft-frontend-saksbehandling: # Gir tilgang til registre innad i nav med ft-frontend-saksbehandling som inngang (PATen bestemmer)
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/ft-frontend-saksbehandling
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - ft-frontend-saksbehandling
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      prod-major-deps:
        dependency-type: "production"
        update-types:
          - "major"
      prod-minor-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-major-deps:
        dependency-type: "development"
        update-types:
          - "major"
      dev-minor-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
