name: Promote
on:
  repository_dispatch:
    types: [promote-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/foreldrepengesoknad
      
jobs:
  promote:
    runs-on: ubuntu-latest
    
    steps:
       
      - name: Set variabler for image og cluster
        run: |
           echo "::set-env name=TAG::$(echo ${{ github.event.client_payload.slash_command.arg1 }} | cut -c16-22)"  
           echo "::set-env name=IMAGE::$IMAGE_BASE:${{ github.event.client_payload.slash_command.arg1 }}" 
           echo "::set-env name=CLUSTER::${{ github.event.client_payload.slash_command.arg2 }}"         
       
      - name: Sjekk ut kode
        uses: actions/checkout@v1
        with:
          ref: ${{ env.TAG }}
    
      - name: Promoter til cluster
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: ${{ env.CLUSTER }}.json 
          
      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    body: '>promote ${{ github.event.client_payload.slash_command.args }} feilet'})
            github.issues.addLabels({...issue, labels: ['deployment','${{ env.CLUSTER }}']})
     
 
      - name: Oppdater kommentar med deployment status
        if: success()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    body: '>promote ${{ github.event.client_payload.slash_command.args }} var OK'})
            github.issues.addLabels({...issue, labels: ['deployment','${{ env.CLUSTER }}']})
   
                  
